# This is the dev profile. This will overwrite any config in the application.yml file
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true