CREATE TABLE IF NOT EXISTS refresh_tokens(
  id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  token VARCHAR(255) NOT NULL,
  expired BOOLEAN NOT NULL,
  user_id BIGINT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);